apiVersion: v1
kind: Pod
metadata:
  name: pod-with-wasm-workload
  annotations:
    run.oci.handler: wasmtime
spec:
  containers:
  - name: wasm-demo-app
    image: quay.io/ifont/wasm-demo-app
    imagePullPolicy: Always
